import type { DealerCoordinates } from "@/types/dealer";

export type DealerCoordinateApproval = {
  dealerId: string;
  coordinates: DealerCoordinates;
  authoritativeAddress: string;
  googleFormattedAddress: string;
  precisionResultType: string;
  classification:
    | "harmless-municipal-variation"
    | "postal-precision-variation"
    | "adjacent-municipality"
    | "geocoder-approximation"
    | "incorrect-geocoder-result";
  reason: string;
  sourceUrls: string[];
  coordinateSource: "official-retailer-structured" | "official-retailer-directions" | "google-storefront-retry";
  reviewedAt: string;
  verificationDecision: "verified";
};

const reviewedAt = "2026-08-15";

export const dealerCoordinateApprovals: DealerCoordinateApproval[] = [
  {
    dealerId: "pga-tour-superstore-greenwood-village-co-united-states",
    coordinates: { latitude: 39.597141, longitude: -104.878133 },
    authoritativeAddress: "9451 East Arapahoe Road, Greenwood Village, CO 80112-3632, United States",
    googleFormattedAddress: "9451 E Arapahoe Rd, Greenwood Village, CO 80111, USA",
    precisionResultType: "Official retailer JSON-LD GeoCoordinates; raw Google result: ROOFTOP street_address/subpremise",
    classification: "postal-precision-variation",
    reason: "The current retailer page publishes the exact verified address and its own GeoCoordinates. Google's differing ZIP does not change the storefront identity, so the retailer-published coordinates take precedence and the authoritative ZIP remains unchanged.",
    sourceUrls: ["https://www.pgatoursuperstore.com/stores/greenwood-village-denver-colorado/0601.html"],
    coordinateSource: "official-retailer-structured",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "pga-tour-superstore-austin-tx-united-states",
    coordinates: { latitude: 30.390129, longitude: -97.732619 },
    authoritativeAddress: "10515 N Mopac Expy, Austin, TX 78759-5324, United States",
    googleFormattedAddress: "10515 N Mopac Expy, Austin, TX 78759, USA",
    precisionResultType: "Official retailer JSON-LD GeoCoordinates; raw Google result: GEOMETRIC_CENTER premise/street_address",
    classification: "geocoder-approximation",
    reason: "The raw building-centroid result remains rejected. The retailer page independently publishes GeoCoordinates beside the exact verified postal address, so those higher-authority coordinates are approved instead.",
    sourceUrls: ["https://www.pgatoursuperstore.com/stores/austin-texas/1218.html"],
    coordinateSource: "official-retailer-structured",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "pga-tour-superstore-woodlands-tx-united-states",
    coordinates: { latitude: 30.182708, longitude: -95.453538 },
    authoritativeAddress: "19075 I-45 S, 105, Shenandoah, TX 77385-8705, United States",
    googleFormattedAddress: "Interstate 45 S, Conroe, TX 77385, USA",
    precisionResultType: "Official retailer JSON-LD GeoCoordinates; raw Google result: partial GEOMETRIC_CENTER route",
    classification: "incorrect-geocoder-result",
    reason: "The raw route-level Conroe result is not used. The current Woodlands store page explicitly identifies the municipality as Shenandoah and publishes GeoCoordinates for the exact verified suite address.",
    sourceUrls: ["https://www.pgatoursuperstore.com/stores/woodlands-shenandoah-texas/1206.html"],
    coordinateSource: "official-retailer-structured",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "scheels-eden-prairie-mn-united-states",
    coordinates: { latitude: 44.8532505, longitude: -93.4258216 },
    authoritativeAddress: "8301 Flying Cloud Dr, Eden Prairie, MN 55344, United States",
    googleFormattedAddress: "8301 Flying Cloud Dr, Eden Prairie, MN 55344, USA",
    precisionResultType: "ROOFTOP SCHEELS establishment/store retry; raw address-only result: GEOMETRIC_CENTER premise/street_address",
    classification: "geocoder-approximation",
    reason: "The address-only building centroid remains rejected. The current SCHEELS page links the exact address to Google Maps, and the full retailer-name plus address retry returned one rooftop SCHEELS storefront at that same address and no competing candidate.",
    sourceUrls: [
      "https://www.scheels.com/store/eden-prairie/098/",
      "https://www.google.com/maps/search/?api=1&query=SCHEELS&query_place_id=ChIJv5k8S58Y9ocR7TdklcaymNo",
    ],
    coordinateSource: "google-storefront-retry",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "club-champion-cherry-hill-nj-united-states",
    coordinates: { latitude: 39.929391, longitude: -75.031554 },
    authoritativeAddress: "706 Haddonfield Road, Cherry Hill, NJ 08002, United States",
    googleFormattedAddress: "706 Haddonfield Rd, Cherry Hill Township, NJ 08002, USA",
    precisionResultType: "Official retailer Get Directions Google Place; raw Google result: ROOFTOP street_address/subpremise",
    classification: "harmless-municipal-variation",
    reason: "Cherry Hill and Cherry Hill Township name the same municipality here. Street, region, and postal code match, and the retailer's own Get Directions link resolves to the Club Champion place at this address.",
    sourceUrls: ["https://clubchampion.com/locations/cherry-hill", "https://maps.app.goo.gl/cWYnPy8wZs4F4gxJ6"],
    coordinateSource: "official-retailer-directions",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "club-champion-west-long-branch-nj-united-states",
    coordinates: { latitude: 40.2922565, longitude: -74.0348778 },
    authoritativeAddress: "310 RT 36, Unit 5, West Long Branch, NJ 07764, United States",
    googleFormattedAddress: "310 NJ-36 #5, Sea Bright, NJ 07760, USA",
    precisionResultType: "Official retailer Get Directions Google Place; raw Google result rejected as incorrect",
    classification: "incorrect-geocoder-result",
    reason: "The original Sea Bright geocode points to a different municipality and ZIP and remains rejected. The current retailer page still lists West Long Branch 07764 and its Get Directions link resolves to the Club Champion place in Consumer Centre at the approved coordinates.",
    sourceUrls: ["https://clubchampion.com/locations/west-long-branch", "https://maps.app.goo.gl/GE4QTC82xFJGhBCj6"],
    coordinateSource: "official-retailer-directions",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "club-champion-tigard-or-united-states",
    coordinates: { latitude: 45.393956, longitude: -122.75051 },
    authoritativeAddress: "7215 SW Hazel Fern Road, Tigard, OR 97224, United States",
    googleFormattedAddress: "7215 SW Hazel Fern Rd, Portland, OR 97224, USA",
    precisionResultType: "Official retailer Get Directions Google Place; raw Google result: ROOFTOP street_address/subpremise",
    classification: "adjacent-municipality",
    reason: "Portland is a Google mailing-locality variation for the exact Tigard street address and ZIP. The retailer page and its linked Club Champion place identify the same physical storefront.",
    sourceUrls: ["https://clubchampion.com/locations/tigard", "https://maps.app.goo.gl/pM413Vm9ffFkQ2gB6"],
    coordinateSource: "official-retailer-directions",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "club-champion-pittsburgh-pa-united-states",
    coordinates: { latitude: 40.447952, longitude: -80.158651 },
    authoritativeAddress: "6563 Steubenville Pike, Pittsburgh, PA 15205, United States",
    googleFormattedAddress: "6563 Steubenville Pike, Pittsburgh, PA 15277, USA",
    precisionResultType: "Official retailer Get Directions Google Place; raw Google result: ROOFTOP street_address/subpremise",
    classification: "postal-precision-variation",
    reason: "The exact street and municipality match. The current retailer page retains ZIP 15205 and links to the same Club Champion place point; the Google ZIP variation is not copied into authoritative dealer data.",
    sourceUrls: ["https://clubchampion.com/locations/pittsburgh", "https://maps.app.goo.gl/CdQcraYJLzosdejR8"],
    coordinateSource: "official-retailer-directions",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "club-champion-columbia-sc-united-states",
    coordinates: { latitude: 34.024066, longitude: -80.950557 },
    authoritativeAddress: "106 Percival Road, Columbia, SC 29203, United States",
    googleFormattedAddress: "106 Percival Rd, Columbia, SC 29206, USA",
    precisionResultType: "Official retailer Get Directions Google Place; raw Google result: ROOFTOP premise/street_address",
    classification: "postal-precision-variation",
    reason: "Street, city, region, and storefront identity match. The retailer page currently publishes 29203 and its directions link resolves to the Jackson Square Club Champion place; the Google postal value is treated as a database variation.",
    sourceUrls: ["https://clubchampion.com/locations/columbia", "https://maps.app.goo.gl/ce6TSXtCqvfE2n3MA"],
    coordinateSource: "official-retailer-directions",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "club-champion-austin-tx-united-states",
    coordinates: { latitude: 30.3368299, longitude: -97.8042941 },
    authoritativeAddress: "3801 N. Capitol of Texas Hwy, Austin, TX 78746, United States",
    googleFormattedAddress: "3801 N Capital of Texas Hwy, Austin, TX 78746, USA",
    precisionResultType: "Official retailer Get Directions Google Place; raw Google result: partial GEOMETRIC_CENTER premise/street_address",
    classification: "geocoder-approximation",
    reason: "The partial building-centroid candidate remains rejected. The current retailer page publishes the verified address and links directly to the Club Champion Austin place point at the approved coordinates.",
    sourceUrls: ["https://clubchampion.com/locations/austin", "https://maps.app.goo.gl/2Vkxbpk6QgsGiHqc7"],
    coordinateSource: "official-retailer-directions",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "club-champion-dallas-tx-united-states",
    coordinates: { latitude: 32.837688, longitude: -96.776252 },
    authoritativeAddress: "5331 E. Mockingbird Lane, Dallas, TX 75206, United States",
    googleFormattedAddress: "5331 E Mockingbird Ln, Dallas, TX 75206, USA",
    precisionResultType: "Official retailer Get Directions Google Place; raw Google result: GEOMETRIC_CENTER premise/street_address",
    classification: "geocoder-approximation",
    reason: "The address-only building centroid remains rejected. The retailer's current page links to the specific Club Champion Dallas Google Place at the same verified address.",
    sourceUrls: ["https://clubchampion.com/locations/dallas", "https://maps.app.goo.gl/CKHKkbi5jmKTR13r9"],
    coordinateSource: "official-retailer-directions",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "club-champion-richmond-va-united-states",
    coordinates: { latitude: 37.651913, longitude: -77.62099 },
    authoritativeAddress: "11747 W. Broad Street, Richmond, VA 23233, United States",
    googleFormattedAddress: "11747 W Broad St, Ridge, VA 23233, USA",
    precisionResultType: "Official retailer Get Directions Google Place; raw Google result: ROOFTOP street_address/subpremise",
    classification: "adjacent-municipality",
    reason: "Ridge/Short Pump is Google's local place name for the exact Richmond mailing address and ZIP. The retailer's directions link resolves to the same Club Champion storefront point.",
    sourceUrls: ["https://clubchampion.com/locations/richmond", "https://maps.app.goo.gl/rG5cRBRY97FvDauW8"],
    coordinateSource: "official-retailer-directions",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "club-champion-basingstoke-united-kingdom",
    coordinates: { latitude: 51.278271, longitude: -1.106974 },
    authoritativeAddress: "Unit 7 Vickers Business Centre, Priestley Road, Basingstoke, Hampshire RG24 9NP, United Kingdom",
    googleFormattedAddress: "Unit 1, Vickers House, Priestley Rd, Basingstoke RG24 9NP, UK",
    precisionResultType: "Official retailer Get Directions Google Place; raw Google establishment result rejected as wrong unit/partial",
    classification: "incorrect-geocoder-result",
    reason: "The raw Unit 1 real-estate result remains rejected. The current dedicated retailer page identifies Unit 7 and RG24 9NP and links to the Club Champion place point at the approved coordinates. The older RG24 9RA snippet is not used; the current page and directions evidence agree on RG24 9NP. The page's 'Priestly' spelling is documented as a retailer typo and does not change the coordinate decision.",
    sourceUrls: ["https://clubchampiongolf.co.uk/locations/basingstoke", "https://goo.gl/maps/MNtMkjSWhQbkmmEEA"],
    coordinateSource: "official-retailer-directions",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "club-champion-heatherton-australia",
    coordinates: { latitude: -37.9705742, longitude: 145.1037503 },
    authoritativeAddress: "385 Centre Dandenong Road, Heatherton, VIC 3202, Australia",
    googleFormattedAddress: "385 Centre Dandenong Rd, Heatherton VIC 3202, Australia",
    precisionResultType: "Official retailer Get Directions Google Place; raw Google result: GEOMETRIC_CENTER premise/street_address",
    classification: "geocoder-approximation",
    reason: "The address-only building centroid remains rejected. The current Melbourne South retailer page links to the specific Club Champion place point at the verified Heatherton address.",
    sourceUrls: ["https://clubchampion.com.au/locations/melbourne-south", "https://maps.app.goo.gl/QPCwce8G2udpvk7R7"],
    coordinateSource: "official-retailer-directions",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "club-champion-mississauga-canada",
    coordinates: { latitude: 43.5386636, longitude: -79.7085232 },
    authoritativeAddress: "3105 Unity Drive, Unit 20, Mississauga, ON L5L 4L2, Canada",
    googleFormattedAddress: "3105 Unity Dr #20, Mississauga, ON L5L 4L3, Canada",
    precisionResultType: "Official retailer Get Directions Google Place; raw Google result: ROOFTOP street_address/subpremise",
    classification: "postal-precision-variation",
    reason: "The exact unit, street, municipality, and province match. The retailer page retains L5L 4L2 and links to the Tour Experience Golf/Club Champion place at the same coordinates; Google's adjacent postal value is not copied into dealer data.",
    sourceUrls: ["https://clubchampion.ca/locations/mississauga", "https://goo.gl/maps/hUiJMxrfeCnKyZaY9"],
    coordinateSource: "official-retailer-directions",
    reviewedAt,
    verificationDecision: "verified",
  },
  {
    dealerId: "club-champion-toronto-canada",
    coordinates: { latitude: 43.746895, longitude: -79.3536758 },
    authoritativeAddress: "31 Scarsdale Road, Unit 3, North York, ON M3B 2R2, Canada",
    googleFormattedAddress: "31 Scarsdale Rd unit 3, North York, ON M3B 3R8, Canada",
    precisionResultType: "Official retailer Get Directions Google Place; raw Google result: ROOFTOP street_address/subpremise",
    classification: "postal-precision-variation",
    reason: "Unit, street, North York locality, and province match. The current retailer page retains M3B 2R2 and its directions link targets the Tour Experience Golf Toronto place at the approved coordinates; Google's postal difference is treated as a database variation.",
    sourceUrls: ["https://clubchampion.ca/locations/toronto"],
    coordinateSource: "official-retailer-directions",
    reviewedAt,
    verificationDecision: "verified",
  },
];
